name: Try to build with Jekyll

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundler
      run: sudo gem install bundler
    - name: Bundle install
      run: bundle install
    - name: Build site
      run: bundle exec jekyll build
